library(ggplot2)
library(reshape2)
library(RColorBrewer)
library(viridis)
library(hexbin)
library(data.table)
library(dplyr)
source('../my_color_palette.R')

###########
## set up stuff: references, colors, analysis tag
###########


args = commandArgs(trailingOnly=TRUE)
tag = args[1]
refs = c("S288c", "CBS432", "N_45", "DBVPG6304", "UWOPS91_917_1") 

rainbow = c("#E13939", "#DA7921", "#E1A939", "#009E2A", "#007CEB", "#8447EB")

ref_colors = c('gray70',
               rainbow[1], rainbow[3], rainbow[5], rainbow[4],
               rainbow[2], "#00A89C") # east west

###########
## loop through all the runs of structure we're interested in
## analyzing individually
###########

for (run_id in c(27)) {

    ##==========
    ## first just make a normal structure plot for each run_id
    ##==========

    ## read in table of
    ## strain/population/fraction/overall_pop_assignment generated by
    ## structure_3_main.py
    a = read.table(paste('/tigress/AKEY/akey_vol2/aclark4/projects/introgression/',
                         'results/analysis/', tag, '/structure/',
                         run_id, '/strain_pop_fracs_k6_run', run_id, '.txt', sep=''),
                   sep='\t', header=T, stringsAsFactors=F)

    ## make 'structure' plot
    ggplot(a, aes(x = reorder(strain, index), y = fraction,
                  fill = as.factor(population))) +
        geom_bar(stat='identity') +
        xlab('strain') +
        ylab('population fraction') + 
        scale_fill_manual(values=rainbow) + 
        theme(panel.background=element_rect(fill="white"),
              panel.grid.minor=element_line(colour="gray92"),
              panel.grid.major=element_line(colour="gray92"),
              axis.line=element_line(),
              axis.title.x = element_text(size=18), 
              axis.title.y = element_text(size=18), 
              axis.text.x = element_text(size=7,angle = 90,
                                         vjust = 1,hjust=1,colour="black"), 
              axis.text.y = element_text(colour="black"))

    ## save in current run's directory
    ggsave(paste('/tigress/AKEY/akey_vol2/aclark4/projects/introgression/',
                 'results/analysis/', tag, '/structure/',
                 run_id, '/strain_pop_fracs_k6_run', run_id, '.png', sep=''),
           width = 16, height = 8, dpi=300)


    ##=========
    ## stacked bar chart, one bar for population background, colored by
    ## paradoxus strain, representing fraction of that background introgressed
    ##=========

    ## read in table of
    ## population/reference/num_bases_intd/frac_bases_intd generated
    ## by struture_3_main.py; in this file, population includes start,
    ## end, and boundaries between population blocks (e.g. '1/3');
    ## reference includes individual references but also
    ## comma-separated combinations
    a = read.table(paste('/tigress/AKEY/akey_vol2/aclark4/projects/introgression/',
                         'results/analysis/', tag, '/structure/',
                         run_id, '/population_introgression_counts_run',
                         run_id, '.txt', sep=''),
                   sep='\t', header=T, stringsAsFactors=F)

    ## get rid of all the weird population categories (start, end, and
    ## in-between regions)
    a = a[(!grepl('/', a$population, fixed=T) &
           a$population != 'start' & a$population != 'end'),]

    ## these are all the individual references plus the two
    ## combinations we care about:
    ## east = refs 2&3 red-orange-gold
    ## west = refs 4&5 blue-teal-green
    sl = c(refs[2], paste(refs[2], refs[3], sep=','), refs[3],
           refs[4], paste(refs[4], refs[5], sep=','), refs[5])
    ## get all the remaining reference entries we don't care about
    ax = unique(a$reference)
    ay = setdiff(ax, sl)
    ## put all the reference entries back together again, with the
    ## ones we care about up front and in order
    sl = c(sl, ay)
    a$reference = factor(a$reference, levels = rev(sl))
    ## color the references we care about appropriately, and make all
    ## the other ones the same gray
    cols = c(c("#E13939", "#DA7921", "#E1A939", "#007CEB", "#00A89C", "#009E2A"),
             rep('gray75', length(sl) - 6))
    cols = rev(cols)
    
    ## get total fraction and number of bases for plotting labels of
    ## total number of bases above each bar at correct location
    frac_totals <- a %>%
        group_by(population) %>%
        summarize(frac_total = sum(frac_bases_introgressed))
    base_totals <- a %>%
        group_by(population) %>%
        summarize(base_total = sum(num_bases_introgressed))
    totals = frac_totals
    totals$base_total = base_totals$base_total
    ## distance above bars to place labels
    shift = max(totals$frac_total) * .05

    ## plot fraction introgressed for each population
    ggplot(a, aes(x = population, y = frac_bases_introgressed,
                  fill = reference)) +
        geom_bar(stat='identity') +
        xlab('population') +
        ylab('fraction introgressed') + 
        geom_label(aes(population, frac_total + shift,
                      label = base_total, fill=NULL), data = totals) +
        scale_fill_manual(values = cols) +
        theme(panel.background=element_rect(fill="white"),
              panel.grid.minor=element_line(colour="gray92"),
              panel.grid.major=element_line(colour="gray92"),
              axis.line=element_line(),
              axis.title.x = element_text(size=18), 
              axis.title.y = element_text(size=18), 
              axis.text.x = element_text(colour="black"), 
              axis.text.y = element_text(colour="black"))

    ## save in directory for this run
    ggsave(paste('/tigress/AKEY/akey_vol2/aclark4/projects/introgression/results/',
                 'analysis/', tag, '/structure/',
                 run_id, '/population_introgression_counts_run',
                 run_id, '.png', sep=''),
           width = 16, height = 8, dpi=300)

    ##=========
    ## for each population background, scatter plot with one column
    ## for each paradoxus reference; for each cerevisiae strain, plot
    ## fraction of the current background that is introgressed from
    ## the current paradoxus strain; sometimes strains will have none
    ## of the background so no point, and sometimes they will have
    ## some of the background but none of it will be introgressed
    ##=========

    ## strain population reference num_bases_introgressed frac_bases_introgressed
    a = read.table(paste('/tigress/AKEY/akey_vol2/aclark4/projects/',
                         'introgression/results/',
                         'analysis/', tag, '/structure/',
                         run_id, '/strain_population_introgression_counts_run',
                         run_id, '.txt', sep=''), 
                   sep='\t', header=T, stringsAsFactors=F)

    ## sum all the categories of introgression by strain and population
    frac_all_totals <- a %>%
        group_by(.dots=c('strain', 'population')) %>%
        summarize(frac_all = sum(frac_bases_introgressed))

    ## get the references and the corresponding part of the table we
    ## care about
    rl = c(refs[2:5],
           paste(refs[2], refs[3], sep=','),
           paste(refs[4], refs[5], sep=','))
    a = a[which(a$reference %in% rl),]

    frac_sub_totals <- a %>%
        group_by(.dots=c('strain', 'population')) %>%
        summarize(frac_sub = sum(frac_bases_introgressed))

    fx = merge(frac_all_totals, frac_sub_totals)
    fx$frac_bases_introgressed = fx$frac_all - fx$frac_sub
    fx$reference = 'other'
    fx$num_bases_introgressed
    fx$frac_all = NULL
    fx$frac_sub = NULL

    d = bind_rows(a, fx)
    d$reference = factor(d$reference, levels = c(rl, 'other'))
    
    for (pop in 1:6) {

        ap = d[which(d$pop == pop),]
        ap$reference = factor(ap$reference, levels = c(rl, 'other'))
        
        ggplot(ap, aes(x=reference, y=frac_bases_introgressed, colour=reference)) +
            geom_jitter(size = 4, alpha=.5, width=.2, height=0) + 
            geom_text(aes(label=as.character(strain)),hjust=0,vjust=0, cex=1) +
            xlab('introgressing reference') +
            ylab('fraction of population background introgressed from reference') + 
            scale_colour_manual(values = c(ref_colors[2:7], 'gray60')) + 
            scale_x_discrete(drop=FALSE) +
            theme(panel.background=element_rect(fill="white"),
                  panel.grid.minor=element_line(colour="gray92"),
                  panel.grid.major=element_line(colour="gray92"),
                  legend.position="none",
                  axis.line=element_line(),
                  axis.title.x = element_text(size=18), 
                  axis.title.y = element_text(size=18), 
                  axis.text.x = element_text(size=16,colour="black"), 
                  axis.text.y = element_text(size=16,colour="black"))

        ## save in directory for this run
        ggsave(paste('/tigress/AKEY/akey_vol2/aclark4/projects/introgression/results/',
                     'analysis/', tag, '/structure/',
                     run_id, '/strain_population_', pop, '_introgression_counts_run',
                     run_id, '.png', sep=''),
               width = 16, height = 8, dpi=300)
    }

    ##=========
    ## plot total amount (fraction) of introgression in each
    ## population background by each strain
    ##=========

    ## group all the fractions for each strain x population together
    ## (sum contribution of all references)
    totals <- a %>%
        group_by(.dots=c('strain', 'population')) %>%
        summarize(num_all=sum(num_bases_introgressed),
                  frac_all=sum(frac_bases_introgressed))


    print(totals[1:10,])
    
    #frac_all = sum(frac_bases_introgressed), num_all = sum(num_bases_introgressed))

    totals = totals[(!grepl('/', totals$population, fixed=T) &
                     totals$population != 'start' &
                     totals$population != 'end'),]
    
    ggplot(totals, aes(x=population, y=frac_all, colour=population, size=num_all)) +
        geom_jitter(alpha=.5, width=.2, height=0) + 
        scale_size_continuous(range=c(2,6)) + 
        geom_text(aes(label=as.character(strain)),hjust=0,vjust=0, cex=1) +
        xlab('population') +
        ylab('fraction of population background introgressed from any reference') + 
        scale_colour_manual(values = rainbow) + 
        #scale_x_discrete(drop=FALSE) +
        theme(panel.background=element_rect(fill="white"),
              panel.grid.minor=element_line(colour="gray92"),
              panel.grid.major=element_line(colour="gray92"),
              legend.position="none",
              axis.line=element_line(),
              axis.title.x = element_text(size=18), 
              axis.title.y = element_text(size=18), 
              axis.text.x = element_text(size=16,colour="black"), 
              axis.text.y = element_text(size=16,colour="black"))
    
    ## save in directory for this run
    ggsave(paste('/tigress/AKEY/akey_vol2/aclark4/projects/introgression/results/',
                 'analysis/', tag, '/structure/',
                 run_id, '/strain_population_introgression_counts_run',
                 run_id, '.png', sep=''),
           width = 16, height = 8, dpi=300)
    
}

########
## the rest of this analysis is just for one run of structure,
## whichever was used to generate blocks_CBS432_p4e2_populations.txt
## by structure_main_3.py
########


########
## NOTES
########

# blocks_CBS432_p4e2_populations.txt contains all the regions that
# passed first stage of filtering but includes regions that we can't
# assign confidently to one species (alternative_states column may
# include more than one species); populations column may include more
# than one population assignment (separated by commas), or may be in a
# region that's between two populations (e.g. 1/3), or may be/include
# start or end

# the simplest way to deal with all this is to take regions only
# assigned to one species, and only assigned to one population (but
# not things like 1/3 or start/end)

# goal is to understand relationship between specific introgressing
# species and population backgrounds

# so basically want grid showing fraction of regions/bases for each
# combination of introgressing species and population background

# or maybe one plot for each introgressing species, violin for each population

############
## for reach reference (and also east and west combinations) plot each
## region's length, grouped by which population background it falls
## within
############

regions = list()
regions_filtered = list()
for (ref in refs[2:5]) {
    regions[[ref]] = read.table(paste('/tigress/AKEY/akey_vol2/aclark4/projects/introgression/results/analysis/', tag, '/blocks_', ref, '_', tag, '_populations.txt', sep=''), sep='\t', header=T, stringsAsFactors=F)
    regions_filtered[[ref]] = regions[[ref]][which(!grepl(',', regions[[ref]]$alternative_states, fixed=T)),]
}

# east = refs 2&3
# west = refs 4&5

regions_west1 = regions[[refs[[2]]]][which(!grepl(refs[[4]], regions[[refs[[2]]]]$alternative_states, fixed=T) & !grepl(refs[[5]], regions[[refs[[2]]]]$alternative_states, fixed=T)),]
regions_west2 = regions[[refs[[3]]]][which(!grepl(refs[[4]], regions[[refs[[3]]]]$alternative_states, fixed=T) & !grepl(refs[[5]], regions[[refs[[3]]]]$alternative_states, fixed=T)),]
regions_filtered[['west']] = rbind(regions_west1, regions_west2)

regions_east1 = regions[[refs[[4]]]][which(!grepl(refs[[2]], regions[[refs[[4]]]]$alternative_states, fixed=T) & !grepl(refs[[3]], regions[[refs[[4]]]]$alternative_states, fixed=T)),]
regions_east2 = regions[[refs[[5]]]][which(!grepl(refs[[2]], regions[[refs[[5]]]]$alternative_states, fixed=T) & !grepl(refs[[3]], regions[[refs[[5]]]]$alternative_states, fixed=T)),]
regions_filtered[['east']] = rbind(regions_east1, regions_east2)

refs = c(refs, c('east', 'west'))

b = data.frame()

for (i in 2:7) {

    ref = refs[i]
    
    ## keep only regions that have been placed unambiguously into a
    ## single population background, and that have passed first round
    ## of filtering to be assigned unambiguously to one introgressing
    ## strain (or to east/west)
    a = regions_filtered[[ref]][
        which(!grepl(',', regions_filtered[[ref]]$population, fixed=T) &
              !grepl('/', regions_filtered[[ref]]$population, fixed=T) &
              !grepl('start', regions_filtered[[ref]]$population, fixed=T) &
              !grepl('end', regions_filtered[[ref]]$population, fixed=T)),]

    
    # plot region lengths for each population background
    ggplot(a, aes(x=as.factor(population), y=end-start+1, colour='x')) +
        geom_jitter(alpha=.4, width=.2, height=0) + 
        xlab('population background containing introgression') +
        ylab('size of introgressed region (bp)') + 
        scale_colour_manual(values = c(ref_colors[i])) + 
        theme(panel.background=element_rect(fill="white"),
              panel.grid.minor=element_line(colour="gray92"),
              panel.grid.major=element_line(colour="gray92"),
              legend.position="none",
              axis.line=element_line(),
              axis.title.x = element_text(size=18), 
              axis.title.y = element_text(size=18), 
              axis.text.x = element_text(colour="black"), 
              axis.text.y = element_text(colour="black"))

    ggsave(paste('/tigress/AKEY/akey_vol2/aclark4/projects/introgression/results/analysis/',tag,'/plots/pops_', ref, '_',tag,'.png', sep=''),
           width = 8, height = 8, dpi=300)

    a$ref = ref
    b = rbind(b, a)
}

##===========
## stacked bar chart, fraction of regions vs ref (including east/west),
## bars colored by population background
##===========

b$ref = factor(b$ref, levels = refs[2:7])

ggplot(b, aes(x = ref, y = end - start + 1, fill = population)) +
    geom_bar(stat='identity') +
    xlab('population background') +
    ylab('amount of introgression') + 
    scale_fill_manual(values=rainbow) + 
    theme(panel.background=element_rect(fill="white"),
          panel.grid.minor=element_line(colour="gray92"),
          panel.grid.major=element_line(colour="gray92"),
          axis.line=element_line(),
          axis.title.x = element_text(size=18), 
          axis.title.y = element_text(size=18), 
          axis.text.x = element_text(size=7,angle = 90,
                                     vjust = 1,hjust=1,colour="black"), 
          axis.text.y = element_text(colour="black"))

ggsave(paste('/tigress/AKEY/akey_vol2/aclark4/projects/introgression/results/analysis/',tag,'/plots/pops_',tag,'.png', sep=''),
           width = 8, height = 8, dpi=300)

